### ISSUE TITLE
Getting error while installing the package

### ISSUE THREAD

**Issue by iamsrpanda** [titancoder/launchbox#1]
PS D:\NODE PROJECT\TitanCoder NPM> launchbox -i
✔ Initialized git repository
Error: Command failed: npm init -y
npm ERR! Invalid name: "TitanCoder NPM"

**npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-11-11T09_28_09_235Z-debug.log**

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm init -y'
}
✔ Failed to initialize project

**Comment by titancoder** [comment]
npm doesn't allow spaces in project name

**Comment by titancoder** [comment]
Will update it with a valid message. Thanks!
